安定性と火力向上モデル
seihirochi/tetris-project pull request #13
Opened 2024-05-08 14:18 UTC by thirofoo

model 関係
- model を大き目に変更
- 画面位置によって即時報酬に倍率がかかるよう変更
- Action の選定アルゴリズムを少し改良
- 特徴量が誤っているところを修正

model 関係以外
- 経験バッファ内のデータの配分の可視化
- ディレクトリ名変更

2024-05-08 14:44 UTC, sor4chi requested changes
まだコード見てないけどとりあえず

2024-05-08 14:44 UTC, sor4chi commented on src/tetris_project/nn/param/README.md
> +  - **報酬倍率**: $ y = \begin{cases} -\frac{3}{2}x + 1.0 & \text{if } x \leq 0.4 \\ -\frac{2}{3}x + \frac{2}{3} & \text{else} \end{cases} $
```suggestion

### 報酬倍率

$$
y = \begin{cases} -\frac{3}{2}x + 1.0 & \text{if } x \leq 0.4 \\ -\frac{2}{3}x + \frac{2}{3} & \text{else} \end{cases}
$$
```

インラインに複数行Tex書けんくない？

2024-05-08 16:37 UTC, thirofoo commented on src/tetris_project/nn/param/README.md
> +  - **報酬倍率**: $ y = \begin{cases} -\frac{3}{2}x + 1.0 & \text{if } x \leq 0.4 \\ -\frac{2}{3}x + \frac{2}{3} & \text{else} \end{cases} $
https://github.com/seihirochi/tetris-project/pull/13/commits/0325fa13faff4936705c4fbd651b5dc6db13f6fd にて修正

2024-05-08 20:39 UTC, sor4chi commented on src/tetris_gym/tetris/tetris.py
> +        # 空マスで自身より上部にあるブロックの数の二乗和
二乗和にしたのは罰則を強めるため？

2024-05-08 20:39 UTC, sor4chi commented on src/tetris_project/nn/NN.py
> +        self.data_line_cnt[experience[5]] += 1
このメンバ5へのアクセスはセグフォしないの？

2024-05-08 20:39 UTC, sor4chi commented on src/tetris_project/nn/NN.py
>          super(NN, self).__init__()
5層にしたのは表現力上げるため？

2024-05-08 20:39 UTC, sor4chi commented on src/tetris_project/nn/param/README.md
> +- $Dense(64) \rightarrow Dense(256) \rightarrow Dense(128) \rightarrow Dense(64) \rightarrow Dense(output\_size)$
レイヤー増やした理由とか書くといいかおm

2024-05-09 03:26 UTC, thirofoo commented on src/tetris_gym/tetris/tetris.py
> +        # 空マスで自身より上部にあるブロックの数の二乗和
その通り。けど最新断面ではその特徴量は使ってない。
とりあえず色々特徴量の取得用関数を追加して、使いたくなったらすぐ使えるようにしてる感じ。

↓ 最新の使用してる特徴量
https://github.com/seihirochi/tetris-project/blob/0325fa13faff4936705c4fbd651b5dc6db13f6fd/src/tetris_gym/tetris/tetris.py#L139-L160

2024-05-09 03:27 UTC, thirofoo commented on src/tetris_project/nn/NN.py
>          super(NN, self).__init__()
That's right.

2024-05-09 03:52 UTC, thirofoo commented on src/tetris_project/nn/param/README.md
> +- $Dense(64) \rightarrow Dense(256) \rightarrow Dense(128) \rightarrow Dense(64) \rightarrow Dense(output\_size)$
https://github.com/seihirochi/tetris-project/pull/13/commits/bce37d280eb61505c776b3be6c17c176c936f8ce にて追記

2024-05-09 03:58 UTC, thirofoo commented on src/tetris_project/nn/NN.py
> +        self.data_line_cnt[experience[5]] += 1
index でメンバ指定するの変だから、https://github.com/seihirochi/tetris-project/pull/13/commits/1f5eb38b262e6218633efca53da01bafcac48922 でBufferItem クラス作って参照綺麗にした。

2024-05-09 08:51 UTC, sor4chi commented on src/tetris_project/nn/NN.py
> +        self.data_line_cnt[experience[5]] += 1
あータプルだったのかw

2024-05-09 08:52 UTC, sor4chi approved these changes

2024-05-09 08:52 UTC, thirofoo commented
thx

2024-05-09 08:56 UTC, merged